### ISSUE TITLE
HTTP Error 302 on speedtest_cli.py --list

### ISSUE THREAD

**Issue by enyone** [sivel/speedtest-cli#135]
```
$ python speedtest_cli.py --list
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "speedtest_cli.py", line 692, in <module>
    main()
  File "speedtest_cli.py", line 686, in main
    speedtest()
  File "speedtest_cli.py", line 517, in speedtest
    servers = closestServers(config['client'], True)
  File "speedtest_cli.py", line 345, in closestServers
    uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  ...cut out lines...
urllib2.HTTPError: HTTP Error 302: The HTTP server returned a redirect error that
would lead to an infinite loop.
The last 30x error message was:
Found
```
```
$ wget http://www.speedtest.net/speedtest-servers-static.php
--2015-02-15 21:29:36--  http://www.speedtest.net/speedtest-servers-static.php
Resolving www.speedtest.net (www.speedtest.net)... 93.184.219.82
Connecting to www.speedtest.net (www.speedtest.net)|93.184.219.82|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
Saving to: ‘speedtest-servers-static.php’
2015-02-15 21:29:38 (751 KB/s) - ‘speedtest-servers-static.php’ saved [850513]
```
```
$ tail speedtest-servers-static.php -n 3
<server url="http://speedtest.cotecal.com.ar/speedtest/upload.php" lat="-50.3370"
lon="-72.2651" name="El Calafate" country="Argentina" cc="AR"
sponsor="COTECAL LTDA." id="2914"
url2="http://speedtest1.cotecal.com.ar/speedtest/upload.php" />
</servers>
</settings>
```
```
$ python speedtest_cli.py --version
0.3.1
```
```
$ python --version
Python 2.7.6
```

**Comment by enyone** [comment]
devel branch works ok
