### ISSUE TITLE
Slow nett gives this error message

### ISSUE THREAD

**Issue by Andersos** [sivel/speedtest-cli#181]
$ speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 764, in <module>
    main()
  File "/usr/local/bin/speedtest-cli", line 758, in main
    speedtest()
  File "/usr/local/bin/speedtest-cli", line 601, in speedtest
    servers = closestServers(config['client'])
  File "/usr/local/bin/speedtest-cli", line 397, in closestServers
    serversxml.append(uh.read(10240))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: ('The read operation timed out',)

**Comment by sivel** [comment]
This is already resolved in the devel version.

**Comment by Andersos** [comment]
Good :)
