### ISSUE TITLE
Thread error

### ISSUE THREAD

**Issue by Mizio66** [sivel/speedtest-cli#197]
Runnin on an Asus Merlin FW:

`Testing download speed.......Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/jffs/scripts/LaMetric/speedtest-cli", line 268, in producer
    thread.start()
  File "/opt/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread`

thanks

M

**Comment by Mizio66** [comment]
ulimit -s  256 was the answer
