### ISSUE TITLE
Empty server list raise a traceback

### ISSUE THREAD

**Issue by Dark-Vex** [sivel/speedtest-cli#228]
The first URL of the server list (www.speedtest.net/speedtest-servers-static.php)
 return an empty webpage and cause the following traceback:

```
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
File "./speedtest_cli.py", line 796, in ?
main()
File "./speedtest_cli.py", line 790, in main
speedtest()
File "./speedtest_cli.py", line 641, in speedtest
servers = closestServers(config['client'])
File "./speedtest_cli.py", line 448, in closestServers
root = DOM.parseString(''.join(serversxml))
File "/usr/lib/python2.4/xml/dom/minidom.py", line 1925, in parseString
File "/usr/lib/python2.4/xml/dom/expatbuilder.py", line 940, in parseString
File "/usr/lib/python2.4/xml/dom/expatbuilder.py", line 223, in parseString
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

In order to get it working I have removed this URL from the speedtest_cli.py file

**Comment by sivel** [comment]
This is already fixed int he branch that will become the next major release.
