### ISSUE TITLE
ssl.SSLError: ('The read operation timed out',)

### ISSUE THREAD

**Issue by buzzijavier** [sivel/speedtest-cli#235]
```
$ speedtest-cli --version
0.3.2
```

```
$ speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 764, in <module>
    main()
  File "/usr/local/bin/speedtest-cli", line 758, in main
    speedtest()
  File "/usr/local/bin/speedtest-cli", line 601, in speedtest
    servers = closestServers(config['client'])
  File "/usr/local/bin/speedtest-cli", line 397, in closestServers
    serversxml.append(uh.read(10240))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: ('The read operation timed out',)
```

this has been happening for at least 2 days now.

**Comment by buzzijavier** [comment]
I just realized that the latest is `0.3.4` -- upgraded. Works great. Disregard.
