### ISSUE TITLE
I am trying to call the speedtest_cli.getConfig() function in a python 3 script and it throws "TypeError: expected string of bytes-like object". It works perfectly under python 2. Exact error inside

### ISSUE THREAD

**Issue by t3zla** [sivel/speedtest-cli#237]
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
    [GCC 5.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import speedtest_cli
    >>> config = speedtest_cli.getConfig()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.5/site-packages/speedtest_cli.py", line 379, in getConfig
        uh, e = catch_request(request)
      File "/usr/lib/python3.5/site-packages/speedtest_cli.py", line 229, in catch_request
        uh = urlopen(request)
      File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.5/urllib/request.py", line 465, in open
        response = self._open(req, data)
      File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
        '_open', req)
      File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 1268, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "/usr/lib/python3.5/urllib/request.py", line 1240, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "/usr/lib/python3.5/http/client.py", line 1083, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.5/http/client.py", line 1123, in _send_request
        self.putheader(hdr, value)
      File "/usr/lib/python3.5/http/client.py", line 1059, in putheader
        if _is_illegal_header_value(values[i]):
    TypeError: expected string or bytes-like object
    >>>

**Comment by sivel** [comment]
The current released version of speedtest-cli was not designed with being used as a python library in mind.

I am working on a new branch which will become the next major version, at https://github.com/sivel/speedtest-cli/pull/212

Please feel free to use the `modularize-2` branch if you need to use this as an importable python module.
