### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by kbruno89** [sivel/speedtest-cli#240]
This script was running normally and stopped working.

Presents this error now (on CentOS 5.5 64 Bits)

Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "./speedtest-cli", line 796, in ?
    main()
  File "./speedtest-cli", line 790, in main
    speedtest()
  File "./speedtest-cli", line 641, in speedtest
    servers = closestServers(config['client'])
  File "./speedtest-cli", line 448, in closestServers
    root = DOM.parseString(''.join(serversxml))
  File "/usr/lib64/python2.4/xml/dom/minidom.py", line 1925, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python2.4/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python2.4/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by sami1979** [comment]
Same here. It looks like there is a problem getting data from URL about the speedtest.
Can anyone narrow this down?

**Comment by sivel** [comment]
This issue should already be resolved in the `modularize-2` branch, which can be seen via https://github.com/sivel/speedtest-cli/pull/212

Feel free to give that a try and let me know if it resolves the problem

https://raw.githubusercontent.com/sivel/speedtest-cli/modularize-2/speedtest.py

**Comment by sami1979** [comment]
@sivel Issue solved. Thanks.
Will that branch be merged with the master in the future?

**Comment by sivel** [comment]
That is my goal.  Performing testing and clean ups, to ensure things work the same, since it is largely a rewrite.

**Comment by kbruno89** [comment]
Thanks!

2016-03-10 13:09 GMT-03:00 Matt Martz <notifications@github.com>:
