### ISSUE TITLE
Traceback Error: load_entry_point()

### ISSUE THREAD

**Issue by WASasquatch** [sivel/speedtest-cli#249]
When running speedtest-cli on Debian Jessie (which for some reason must be ran as `/usr/local/bin/speedtest-cli`)
```
Traceback (most recent call last):
  File "./speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==0.3.4', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
```

**Comment by sivel** [comment]
You seem to have a setuptools issue on your server.  Maybe just try downloading the speedtest_cli.py file and running it without installation.

**Comment by WASasquatch** [comment]
Does it require python3 rather then 5.5.x?
