### ISSUE TITLE
stopped working on an old CentOS 5.x, with Python 2.4.3

### ISSUE THREAD

**Issue by kb9mwr** [sivel/speedtest-cli#328]
~/test $ ./speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "./speedtest-cli", line 796, in ?
    main()
  File "./speedtest-cli", line 790, in main
    speedtest()
  File "./speedtest-cli", line 641, in speedtest
    servers = closestServers(config['client'])
  File "./speedtest-cli", line 448, in closestServers
    root = DOM.parseString(''.join(serversxml))
  File "/usr/lib/python2.4/site-packages/_xmlplus/dom/minidom.py", line 1925, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.4/site-packages/_xmlplus/dom/expatbuilder.py", line 942, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.4/site-packages/_xmlplus/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by sivel** [comment]
Please give the devel branch a try and see if the changes made there already resolve your problem.

https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py

**Comment by kb9mwr** [comment]
Works, thank you!

**Comment by sivel** [comment]
Great, I'll go ahead and close this.  I hope to release the devel branch soon.
