### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by dbrosy** [sivel/speedtest-cli#355]
I have installed this script on 3 edgerouters with success on 2.
On the third i get the following error:

`Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest", line 1412, in <module>
    main()
  File "/usr/local/bin/speedtest", line 1402, in main
    shell()
  File "/usr/local/bin/speedtest", line 1312, in shell
    speedtest = Speedtest()
  File "/usr/local/bin/speedtest", line 685, in __init__
    self.get_config()
  File "/usr/local/bin/speedtest", line 710, in get_config
    stream = get_response_stream(uh)
  File "/usr/local/bin/speedtest", line 417, in get_response_stream
    return GzipDecodedResponse(response)
  File "/usr/local/bin/speedtest", line 296, in __init__
    self.io = IO(response.read())
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
socket.timeout: timed out
`

I am aware that the internet connection has some issues so i am not surprised at the error. I just thought it might be handled better. 

Is it possible to handle the error and give a meaningful result?

Note: I have renamed speedtest-cli to just speedtest to save on typing :)

**Comment by sivel** [comment]
This should already be resolved in devel which you can get at https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py

Download and try.

**Comment by dbrosy** [comment]
Awesome, just tested and looks good.

thanks for quick response
