### ISSUE TITLE
UnicodeEncodeError when list the server in Prague

### ISSUE THREAD

**Issue by aik-jahoda** [sivel/speedtest-cli#362]
When run ./speedtest-cli --list from Prague the server list ends with following error:

```
Traceback (most recent call last):
  File "./speedtest-cli", line 1428, in <module>
    main()
  File "./speedtest-cli", line 1418, in main
    shell()
  File "./speedtest-cli", line 1346, in shell
    print_(line)
  File "./speedtest-cli", line 204, in print_
    write(arg)
  File "./speedtest-cli", line 169, in write
    data = data.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u011b' in position 22: ordinal not in range(128)
```

I suppose it fails because of this server:
`<server url="http://rychlost.rtyne.net/speedtest/upload.php" lat="50.5058" lon="16.0686" name="Rtyně v Podkrkonoší" country="Czech Republic" cc="cz" sponsor="Rtyne.net" id="3452" url2="http://rychlost_b.rtyne.net/speedtest/upload.php" host="31.133.8.20:8080"/>`

as there is a string with non ascii character: "Rtyně v Podkrkonoší"

**Comment by ylluminate** [comment]
Same error with Los Angeles, California: `$ speedtest-cli --list`
```
Retrieving speedtest.net configuration...
 5827) Time Warner Cable (Los Angeles, CA, United States) [2.74 km]
 3226) Race Communications (Los Angeles, CA, United States) [2.74 km]
 2953) Atlantic Metro (Los Angeles, CA, United States) [2.74 km]
 7456) QuadraNet, Inc (Los Angeles, CA, United States) [2.74 km]
 6047) Phyber Communications (Los Angeles, CA, United States) [2.74 km]
 5905) GigeNET (Los Angeles, CA, United States) [2.74 km]
 7244) psychz.net (Los Angeles, CA, United States) [2.74 km]
 5861) WebNX (Los Angeles, CA, United States) [2.74 km]
10392) Speedtest.net (Los Angeles, CA, United States) [2.74 km]
 5602) HugeServer Networks, LLC (Los Angeles, CA, United States) [2.74 km]
 5303) Host Duplex (Los Angeles, CA, United States) [2.74 km]
 3883) SingTel (Los Angeles, CA, United States) [2.74 km]
 6248) GorillaServers (Los Angeles, CA, United States) [2.74 km]
 7190) Sharktech Inc. (Los Angeles, CA, United States) [2.74 km]
 7048) FPT Telecom (Los Angeles, CA, United States) [2.74 km]
 3864) California Internet Solutions (Los Angeles, CA, United States) [2.74 km]
10269) Interoute VDC (Los Angeles, CA, United States) [2.74 km]
10564) Speedtest.net (Los Angeles, CA, United States) [2.74 km]
 9916) fdcservers.net (Los Angeles, CA, United States) [2.74 km]
10760) https://fdcservers.net (Pasadena, CA, United States) [15.81 km]
 7017) C3Network.Inc (Diamond Bar, CA, United States) [42.60 km]
 5362) Siteserver, Inc. (Simi Valley, CA, United States) [48.60 km]
 2426) I2B Networks Inc (San Diego, CA, United States) [182.06 km]
 2969) ScaleMatrix (San Diego, CA, United States) [182.06 km]
  948) FastServ Networks LLC (San Diego, CA, United States) [182.06 km]
10878) M5 Hosting (San Diego, CA, United States) [182.06 km]
 3193) Triara (Tijuana, Mexico) [206.21 km]
 3955) Totalplay (Tijuana, Mexico) [206.21 km]
 6559) TRANSTELCO (Tijuana, Mexico) [206.21 km]
 7953) AT&T Mexico (Tijuana, Mexico) [206.21 km]
10039) Mexico Internet Exchange (Tijuana, Mexico) [206.21 km]
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==1.0.2', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.6/site-packages/speedtest_cli-1.0.2-py2.6.egg/speedtest.py", line 1418, in main
    shell()
  File "/usr/lib/python2.6/site-packages/speedtest_cli-1.0.2-py2.6.egg/speedtest.py", line 1346, in shell
    print_(line)
  File "/usr/lib/python2.6/site-packages/speedtest_cli-1.0.2-py2.6.egg/speedtest.py", line 204, in print_
    write(arg)
  File "/usr/lib/python2.6/site-packages/speedtest_cli-1.0.2-py2.6.egg/speedtest.py", line 169, in write
    data = data.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 19: ordinal not in range(128)
```

**Comment by sivel** [comment]
Can you confirm whether the following changes anything for you:

```
speedtest-cli --list | cat
```

I cannot duplicate the issue, and I am wondering whether that has to do with `stdout` having a different encoding.  On my system I have:

```
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```

And everything works fine for me.  When piping to cat, the code should assign `UTF-8` as the encoding.

**Comment by aik-jahoda** [comment]
You are right, the redirect to cat works well. 
I realised on my system (OpenWRT - turris.cz) there is no LC_ALL nor LANG environment variable.

**Comment by ylluminate** [comment]
FWIW, `speedtest-cli --list` at the previous failing location in California is no longer crashing... I can only suspect that the listing changed for me.

**Comment by aik-jahoda** [comment]
It is still crashing on my side. At least we have repro steps.

**Comment by sivel** [comment]
I think it is probably safe, for me to just set the encoding as `utf8` always.  I need to test some more, but will have to get a test environment for a reproducer.

**Comment by sivel** [comment]
Ok, so I can easily duplicate this with:

```
$ LC_ALL=C LANG=C python speedtest.py --list
[...]
Traceback (most recent call last):
  File "speedtest.py", line 1438, in <module>
    main()
  File "speedtest.py", line 1428, in main
    shell()
  File "speedtest.py", line 1354, in shell
    print_(line)
  File "speedtest.py", line 204, in print_
    write(arg)
  File "speedtest.py", line 169, in write
    data = data.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 17: ordinal not in range(128)
```

**Comment by sivel** [comment]
I can confirm with the above commit, that forcing UTF-8 resolves the problem, even when specifying `LC_ALL=C LANG=C`.

**Comment by aik-jahoda** [comment]
I can confirm it works on my side. Thank you!
