### ISSUE TITLE
Unicode error when setting output to csv since 1.04

### ISSUE THREAD

**Issue by elperepat** [sivel/speedtest-cli#385]
I was using speedtest-cli, but now when I try to send the output to a csv file using the --csv flag, I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1465, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1453, in shell
    print_(results.csv(delimiter=args.csv_delimiter))
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 706, in csv
    data['upload']])
TypeError: unicode argument expected, got 'str'

All was fine using 1.03

Using Python 2.7.6 on ubuntu 14.04
Same result on Python Python 2.7.12 on Mint 18.1

**Comment by sivel** [comment]
This should be resolved in the devel branch now.

You can test be downloading https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py and running that file:

```
python speedtest.py --csv
```

**Comment by elperepat** [comment]
Yep, working properly!

Thanks
