### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Suncatcher** [sivel/speedtest-cli#398]
I get this error, like they got before ([1]https://github.com/sivel/speedtest-cli/issues/87), [2](https://github.com/sivel/speedtest-cli/issues/269)), years before.

        pip3 install speedtest-cli
        Collecting speedtest-cli
          Downloading speedtest_cli-1.0.6-py2.py3-none-any.whl
        Installing collected packages: speedtest-cli
        Successfully installed speedtest-cli-1.0.6
        root@bodhi-v:/home/suncatcher# speedtest-cli --simple
        Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/speedtest.py", line 1432, in shell
            speedtest.get_servers(servers)
          File "/usr/local/lib/python3.5/dist-packages/speedtest.py", line 885, in get_servers stream = get_response_stream(uh)
          File "/usr/local/lib/python3.5/dist-packages/speedtest.py", line 471, in get_response_stream
            return GzipDecodedResponse(response)
          File "/usr/local/lib/python3.5/dist-packages/speedtest.py", line 339, in __init__chunk = response.read(1024)
          File "/usr/lib/python3.5/http/client.py", line 448, in read n = self.readinto(b)
          File "/usr/lib/python3.5/http/client.py", line 488, in readinto n = self.fp.readinto(b)
          File "/usr/lib/python3.5/socket.py", line 575, in readinto return self._sock.recv_into(b) socket.timeout: timed out
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/local/bin/speedtest-cli", line 11, in <module> sys.exit(main())
          File "/usr/local/lib/python3.5/dist-packages/speedtest.py", line 1494, in main shell()
          File "/usr/local/lib/python3.5/dist-packages/speedtest.py", line 1435, in shell except (ServersRetrievalError, HTTP_ERRORS):
        TypeError: catching classes that do not inherit from BaseException is not allowed
        root@bodhi-v:/home/suncatcher#

**Comment by sivel** [comment]
The exception has already been resolved in the branch that will become the next release.  In the mean time, the exception would still create an error, just a nicer error.

Try running with `--debug` and that may help indicate a problem.

In the end, your issue is network related, where you are having issues downloading the speedtest configs.

**Comment by Suncatcher** [comment]
What means "my issue is network related"? The network working just fine.
