### ISSUE TITLE
ERROR: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by busa92** [sivel/speedtest-cli#405]
They change urls?
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: HTTP Error 404: Not Found

**Comment by mikesand** [comment]
Same here.

**Comment by evralston** [comment]
Looks like Speedtest is explicitly blocking requests with speedtestcli's user-agent header.

Workaround that worked for me was changing `USER_AGENT = None` to `USER_AGENT = 'random string'`

**Comment by rpe1313** [comment]
Modify lines 394 thru 400
`    ua_tuple = (
        'Mozilla/5.0',
        '(%s; U; %s; en-us)' % (platform.system(), platform.architecture()[0]),
        'Gecko/20100101',
        '(KHTML, like Gecko)',
        'Firefox/53.0'
    )`

**Comment by sashkab** [comment]
Actual error, in case someone wants to see it was:

```python
Traceback (most recent call last):
  File "/home/user/.virtualenvs/3/lib/python3.6/site-packages/speedtest.py", line 1368, in shell
    speedtest = Speedtest()
  File "/home/user/.virtualenvs/3/lib/python3.6/site-packages/speedtest.py", line 726, in __init__
    self.get_config()
  File "/home/user/.virtualenvs/3/lib/python3.6/site-packages/speedtest.py", line 748, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.virtualenvs/3/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/3/lib/python3.6/site-packages/speedtest.py", line 1465, in main
    shell()
  File "/home/user/.virtualenvs/3/lib/python3.6/site-packages/speedtest.py", line 1369, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed
```

And suggestion by @rpe1313 worked, but ensure you're on latest version of the speedtest-cli.

**Comment by JohnRobson** [comment]
`$ speedtest-cli --bytes --secure --share
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.6', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1398, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed


$ sudo speedtest-cli --bytes --secure --share
[sudo] password for us: 
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.6', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1398, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed
`

**Comment by JohnRobson** [comment]
$ speedtest-cli --bytes --secure --share
```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 404: Not Found
```
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.6', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1398, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed
```

$ sudo speedtest-cli --bytes --secure --share
```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: HTTP Error 404: Not Found
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.6', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/usr/lib/python3.6/site-packages/speedtest.py", line 1398, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by rpe1313** [comment]
@JohnRobson updating the lines above in 1.0.6 will remove this error. The error is occurring because the config cannot be downloaded from speedtest.net.

**Comment by dylancarruthers** [comment]
Can you do a pull request for your change?

**Comment by brennentsmith** [comment]
Speedtest engineering here (check my profile) - speedtest-cli traffic was flagged as malicious and blocked, I've since pushed a fix to the edge. Should be live soon.

**Comment by PeterDaveHello** [comment]
This home-made patch will help you bypass the user agent detection and speedtest-cli blocking 😄 

```diff
diff --git a/speedtest.py b/speedtest.py
index 8b8526a..811d848 100755
--- a/speedtest.py
+++ b/speedtest.py
@@ -388,6 +388,7 @@ def build_user_agent():
     """Build a Mozilla/5.0 compatible User-Agent string"""

     global USER_AGENT
+    USER_AGENT = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
     if USER_AGENT:
         return USER_AGENT
```

**Comment by brennentsmith** [comment]
Update from Speedtest engineering - the rule has just started to roll out and should be global soon. 

For those that changed their UA's, I'd highly recommend switching back to the default speedtest-cli UserAgent.

**Comment by rpe1313** [comment]
@PeterDaveHello in order to conform with standards the User-Agent should contain the actual OS and arch type for dissemination. Although, in the initial script Python is mentioned, the actual layout should appear to the speedtest.net server as Python is not the browser moreover it is the compiler. 
 
`Mozilla/5.0 (<OS>; <ARCH>; rv:<speedtest-cli ver>) Gecko/20100101 (KHTML, like Gecko) speedtest-cli`

**Comment by sashkab** [comment]
> compiler

Python actually is [interpreter](https://www.python.org/doc/essays/blurb/).

Updated my pull request #406 as suggested.

**Comment by PeterDaveHello** [comment]
@rpe1313 that's just a workaround method, feel free to modify as you need/want :) And as @brennentsmith says, I believe that it'll be fixed soon.

**Comment by brennentsmith** [comment]
At this point - the rule should be fully rolled out. Please post here if anyone is still getting 404's (for both regular and `--secure`)
