### ISSUE TITLE
Error running speedtest-cli

### ISSUE THREAD

**Issue by GCM707** [sivel/speedtest-cli#408]
Installed via git, Getting the following:
sudo speedtest-cli
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==1.0.6', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named speedtest

sudo python -V
Python 2.7.9

sudo lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie

**Comment by Gelo5** [comment]
+1
Same problem. Same configuration.
Traceback (most recent call last):
File "/usr/local/bin/speedtest-cli", line 9, in <module>
load_entry_point('speedtest-cli==1.0.6', 'console_scripts', 'speedtest-cli')()
File "build/bdist.linux-armv7l/egg/pkg_resources.py", line 356, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "build/bdist.linux-armv7l/egg/pkg_resources.py", line 2439, in load_entry_point
File "build/bdist.linux-armv7l/egg/pkg_resources.py", line 2155, in load
parts.pop()
ImportError: No module named speedtest

**Comment by Gelo5** [comment]
sudo speedtest-cli/speedtest.py

**Comment by GCM707** [comment]
hm yeah it works when ran that way.

**Comment by sivel** [comment]
Installation error, not a problem with speedtest-cli

**Comment by dylanh724** [comment]
I have this issue too. With the exact same error -- however, speedtest-cli/speedtest.py doesn't seem to work. I think the readme needs updating.

**Comment by bitinerant** [comment]
This work-around fixed the issue for me--I could run speedtest-cli as a normal user after running:
`sudo chmod o+r /usr/local/lib/python2.7/dist-packages/*`
