### ISSUE TITLE
BaseException Error on Windows

### ISSUE THREAD

**Issue by petedaws** [sivel/speedtest-cli#410]
Got the following exception when running on Windows 10. Python 3.5

`Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\peter\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Peter\AppData\Local\Programs\Python\Python35\Scripts\speedtest-cli.exe\__main__.py", line 9, in <module>
  File "c:\users\peter\appdata\local\programs\python\python35\lib\site-packages\speedtest.py", line 1494, in main
    shell()
  File "c:\users\peter\appdata\local\programs\python\python35\lib\site-packages\speedtest.py", line 1398, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed`

**Comment by sivel** [comment]
This is resolved in the branch that will become the next release.
