### ISSUE TITLE
MemoryError on linux/mipsel system and python 2.7.3

### ISSUE THREAD

**Issue by vchrizz** [sivel/speedtest-cli#412]
thanks for this great script! works really nice!
on Ubiquiti ER-X series routers just the upload-test does not work:
(download-test works perfectly. mipsel linux system, python 2.7.3)

```
user@test-router:~$ free -m
             total       used       free     shared    buffers     cached
Mem:           249        191         57          0         27         93
-/+ buffers/cache:         70        178
Swap:            0          0          0
user@test-router:~$ ./speedtest.py --no-download --simple
Skipping download test
Traceback (most recent call last):
  File "./speedtest.py", line 1504, in <module>
    main()
  File "./speedtest.py", line 1494, in main
    shell()
  File "./speedtest.py", line 1466, in shell
    speedtest.upload(callback=callback, pre_allocate=args.pre_allocate)
  File "./speedtest.py", line 1151, in upload
    data.pre_allocate()
  File "./speedtest.py", line 551, in pre_allocate
    (chars * multiplier)[0:int(self.length) - 9]
MemoryError

```

**Comment by sivel** [comment]
Use `--no-pre-allocate`
