### ISSUE TITLE
TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by yodaphone** [sivel/speedtest-cli#431]
Hi

running this on FreeBSD 11. used the pkg to install this.

when i run without --csv it runs just fine but when i do this

speedtest-cli --csv

i get this error

Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.4', 'console_scripts', 'speedtest-cli')()
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 1465, in main
    shell()
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 1453, in shell
    print_(results.csv(delimiter=args.csv_delimiter))
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 706, in csv
    data['upload']])
TypeError: unicode argument expected, got 'str'

**Comment by sivel** [comment]
I believe that should be fixed since 1.0.5.  The current version is 1.0.6.  Please upgrade.
