### ISSUE TITLE
Error while forcing source

### ISSUE THREAD

**Issue by moallemi** [sivel/speedtest-cli#433]
I am running speedtest-cli  on a raspberry pi 3. when I force the source, following exception raises:

eth0 => 192.168.25.178
wan1 => 192.168.1.129
/speedtest.py --source 192.168.1.129
```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "speedtest.py", line 743, in __init__
    self.get_config()
  File "speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
__main__.ConfigRetrievalError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedtest.py", line 1504, in <module>
    main()
  File "speedtest.py", line 1494, in main
    shell()
  File "speedtest.py", line 1398, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by sivel** [comment]
The traceback is fixed in the upcoming release.

There is still an error, in that trying to fetch the config, while trying to bind to 192.168.1.129 caused a timeout accessing the file.

**Comment by moallemi** [comment]
I got this error when trying to set an interface other than default. In my case when I use wan0 or wan1 ip this error happens

**Comment by AlexGrs** [comment]
It seems the error is not fixed, i Have it each time I want to test from a different source than the default one.

```
python speedtest.py --source 10.14.174.218
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "speedtest.py", line 1401, in shell
    speedtest = Speedtest()
  File "speedtest.py", line 743, in __init__
    self.get_config()
  File "speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
__main__.ConfigRetrievalError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speedtest.py", line 1508, in <module>
    main()
  File "speedtest.py", line 1498, in main
    shell()
  File "speedtest.py", line 1402, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by sivel** [comment]
It's fixed, just not in the released version.  Your problem however is: `urlopen error timed out`

So regardless of the traceback, the IP you provided for `--source` does not work.
