### ISSUE TITLE
upload speed test outputs error

### ISSUE THREAD

**Issue by danieldude15** [sivel/speedtest-cli#437]
speedtest-cli
Retrieving speedtest.net configuration...
Testing from Bezeq (--.--.--.--)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Partner (Rosh HaAyin) [8.04 km]: 118.21 ms
Testing download speed................................................................................
Download: 9.04 Mbit/s
Testing upload speedTraceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.0', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1494, in main
    shell()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1466, in shell
    speedtest.upload(callback=callback, pre_allocate=args.pre_allocate)
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1151, in upload
    data.pre_allocate()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 551, in pre_allocate
    (chars * multiplier)[0:int(self.length) - 9]
MemoryError

**Comment by sivel** [comment]
The machine you are running from has insufficient memory, please read the README, man page, or use `-h`.

```
--no-pre-allocate
```

**Comment by danieldude15** [comment]
its a raspberry pi. thank you for your help 💯
