### ISSUE TITLE
Speedtest broke (at the servers) about noon today (UTC16)

### ISSUE THREAD

**Issue by glyndon** [sivel/speedtest-cli#439]
As of UTC16 today, speedtest-cli returns the below.
Based on a --debug test, it appears that what's being returned from the server no longer resembles what the cli tool is expecting to see.

$ speedtest-cli
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.0', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1400, in main
    shell()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1310, in shell
    speedtest = Speedtest()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 685, in __init__
    self.get_config()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 725, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 3, column 67

**Comment by samwiseg00** [comment]
I am getting the same thing... 

```
$ speedtest --debug
DEBUG: Mozilla/5.0 (Darwin; U; 64bit; en-us) Python/2.7.14 (KHTML, like Gecko) speedtest-cli/1.0.2
Retrieving speedtest.net configuration...
DEBUG: GET http://www.speedtest.net/speedtest-config.php?x=1507776126379.
DEBUG: <?xml version="1.0" encoding="UTF-8"?>
<settings>
<client ip="x.x.x.x" lat="xx.xxx" lon="-xx.xxx" isp="ISP" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="US" />
<server-config threadcount="4" ignoreids="683,1525,1716,1758,1762,1816,1834,1839,1840,1850,1854,1859,1860,1861,1871,1873,1875,1880,1902,1913,3280,3383,3448,3695,3696,3697,3698,3699,3725,3726,3727,3728,3729,3730,3731,3733,3788,4140,4533,4787,5085,5086,5087,5894,6130,6285,6397,6398,6412,7326,7334,7529,8591,9245,9816,10221,10226,10556,10557,10558,10561,10562,10563,10564,10565,10566,10567,10901,10923,11201,11736,11737,11792,12688,12689,12861,12862,12863,13362,14209,949,5249" notonmap="10413,5718,6051,4139,10309,4231,9644,11076,4810,4247,12549,12776,2610,5654,5834,2151,8009,8455,8670,6814,6866,5681,6616,1930,4503,11424,3170,4472,6307,4984,5201,8486,12824,10366,6053,6827,8367,11266,9321,12363,13851,13185,10025,10045,8205,2557,5950,6389,13152,7303,1728,11789,7532,3326,4521,3777,10323,3704,13515,14091,13708,1543,6118,9913,10258,11611,9147,12506,11365,13040,13444,13291,9616,6440,2636,1894,13953,14678,10586,8399,11883,7619,5284,8066,6032,9886,10026,10262,5911,11123,7437,7352,11547,8281,12260,12920,5679,11965,6578,5447,5121,6312,9264,8478,7743,6195,12212,2518,9332,3585,8040,12974,9597,9788,8497,8223,10053,3989,11181,11290,11465,6394,8218,5305,4683,10265,1688,11977,12746,10176,10770,3620,6070,9084,7412,6635,12777,4580,4768,13178,5904,6057,6029,8879,11329,4246,4149,13984,10899,2796,12319,11983,13667,10409,8155,4393,1993,12154,12723,5502,11776,4388,8211,3997,10264,11675,13421,2477,10082,1008,10703,11579,14476,4290,4111,9709,4590,6049,7609,9836,8107,7758,4089,14137,11788,11608,13294,826,2565,4441,3860,7537,5210,7384,4049,13238,13454,10763,14089,9035,7829,13898,3805,10097,7440,13428,12081,7617,6973,10754,11348,5463,3676,6485,2605,11805,11842,14671,10050,5919,8705,3084,7193,12012,11750,11015,12086,2452,7323,6672,3287,10994,10261,12619,13873,12536,9869,11250,11256,7246,2206,12652,8863,10116,12927,6030,10268,7170,10546,10591,7546,9612,9933,6474,10263,6583,8109,11219,12283,12961,12417,13292,13419,4168,1036,7983,10152,4332,11186,7192,8404,12031,8228,10241,10572,10667,11343,4317,8224,4606,7970,2058,6272,13298,7640,6722,8339,9942,5098,5875,6855,12801,3007,7456,3883,11482,5303,6047,5861,7244,6248,10269,5905,13301,13516,9916,7048,7190,13436,10207,11953,6570,11383,10575,6561,3165,8707,12407,13653,13655,11744,3567,12885,9003,6074,4975,12078,12303,8706,12244,9384,12823,10878,6900,12882,3529,11173,13635,11743,7024,1915,12480,4081,9930,8882,7382,9089,8956,10952,10193,9334,7859,8631,11036,8906,11876,10444,10801,10839,10181,12497,9570,7236,13108,10549,7075,13167,12384,11720,10651,5217,11272,6558,12060,6139,6782,11662,12215,5942,10471,12582,12595,5315,5661,7429,11703,12735,5219,11704,12596,12583,9118,7915,11771,8148,7687,8626,11705,12597,5854,12000,6597,7076,11707,6391,12585,2595,12599,12587,3458,10424,4588,3366,5020,9096,5260,11928,7810,13242,12204,4773,12588,8002,12589,12600,12590,5853,8968,11713,12601,7507,7198,7215,10308,14061,11194,9903,2428,11430,2552,10322,13675,14133,6898,5993,5415,11238,8079,11791,9764,7605,9584,6454,9049,6403,8308,5060,8122,7950,8659,12843,10800,6746,4883,12775,10913,7128,6749,3984,5079,4491,5779,5311,6783,9995,10631,12977,12951,6261,7319,11322,5329,9455,12718,14062,13418,14059,13122,9724,11865,7805,12210,4229,10685,3147,5609,7662,1219,7115,5394,6521,5431,11528,12443,11823,6283,8610,9591,10481,10077,6455,11562,9556,8797,7231,2583,12182,11117,9799,11413,10346,11361,4706,11468,4663,7784,8448,9282,11014,6756,13202,9966,12973,12227,10491,9388,6610,8760,4182,8615,5828,10574,10798,11248,9509,13280,13093,12409,13459,12995,8466,8158,3381,9668,11342,2427,12277,12635,12473,12406,9994,11411,12810,13852,10382,11145,4836,12208,7295,11846,11318,12459,8632,6537,10689,8616,12942,13612,6858,7698,9652,3917,13671,14082,4348,4956,11850,8700,7009,5935,5304,7311,9575,7368,6341,10769,11360,7046,10518,9215,8235,10875,7881,13457,8548,7152,7935,13077,10517,8291,8229,13569,11102,12470,12984,13182,8288,13986,11255,9021,7217,12324,11435,13558,8545,10780,6370,11664,10605,10352,12416,13398,7804,8841,10494,7582,6612,7959,8874,5356,6281,10810,7410,5248,9856,11033,10239,11118,10062,12909,11052,11894,9495,8828,7680,13954,10711,7272,10730,11172,10966,5909,13341,6110,11319,8261,9097,9693,7292,12197,7370,7397,4958,12006,4909,2157,12099,11969,10958,8370,6535,12045,11960,13566,9344,2952,11840,12707,8927,12561,9221,7059,9959,12691,10043,13582,9767,8152,11012,11793,11995,12105,11996,10879,14071,9266,11288,13029,7816,11499,6829,12988,11567,6533,12814,11064,8091,13982,14400,11211,11549,7612,10656,4899,5672,11488,12322,12399,8290,12996,12668,3367,8732,8570,6246,7254,10312,6688,12286,11310,9227,5889,12010,13229,13780,12088,1714,8794,10333,8749,5205,6200,13278,1931,9222,8793,12732,13065,2582,6355,5666,2173,5744,11767,14329,13474,13425,5921,7318,8894,5868,10337,9682,5203,6093,12373,13921,8453,900,6825,5181,11480,4336,10825,5074,13277,5749,8345,5539,4775,7393,10179,9345,12651,8855,13676,12440,12932,6141,2169,13057,10592" forcepingid="" preferredserverid=""/>
<licensekey>f7a45ced624d3a70-1df5b7cd427370f7-b91ee21d6cb22d7b</licensekey>
<customer>speedtest</customer>
<odometer start="10197790263" rate="20"/>
<times dl1="5000000" dl2="35000000" dl3="800000000" ul1="1000000" ul2="8000000" ul3="35000000"/>
<download testlength="10" initialtest="250K" mintestsize="250K" threadsperurl="4"/>
<upload testlength="10" ratio="5" initialtest="0" mintestsize="32K" threads="2" maxchunksize="512K" maxchunkcount="50" threadsperurl="4"/>
<latency testlength="10" waittime="50" timeout="20"/>
<socket-download testlength="15" initialthreads="4" minthreads="4" maxthreads="32" threadratio="750K" maxsamplesize="5000000" minsamplesize="32000" startsamplesize="1000000" startbuffersize="1" bufferlength="5000" packetlength="1000" readbuffer="65536"/>
<socket-upload testlength="15" initialthreads="dyn:tcpulthreads" minthreads="dyn:tcpulthreads" maxthreads="32" threadratio="750K" maxsamplesize="1000000" minsamplesize="32000" startsamplesize="100000" startbuffersize="2" bufferlength="1000" packetlength="1000" disabled="false"/>
<socket-latency testlength="10" waittime="50" timeout="20"/>
<conditions>
<cond name="tcpulthreads" download="+100000" value="8" />
<cond name="tcpulthreads" download="+10000" value="4" />
<cond name="tcpulthreads" value="2" />
</conditions><interface template="mbps" colortcp="0" />
<translation lang="xml" >
<text id="rateyourisp">Rate Your ISP</text>
<text id="copy">COPY IP</text>
<text id="long-kbps">kilobits</text>
<text id="long-Mbps">megabits</text>
<text id="newserver">NEW SERVER</text>
<text id="testagain">TEST AGAIN</text>
<text id="uploadspeed">UPLOAD SPEED</text>
<text id="downloadspeed">DOWNLOAD SPEED</text>
<text id="kbps">kbps</text>
<text id="Mbps">Mbps</text>
<text id="begintest">BEGIN TEST</text>
<text id="startclosest">START TEST TO RECOMMENDED SERVER</text>
<text id="long-MB/s">megabytes</text>
<text id="long-kB/s">kilobytes</text>
<text id="kB/s">kB/s</text>
<text id="MB/s">MB/s</text>
<text id="mbps">Mbps</text>
<text id="ratinghelp">How happy are you with your current Internet service provider?</text>
<text id="rating1">Very unhappy</text>
<text id="rating2">Unhappy</text>
<text id="rating3">Neutral</text>
<text id="rating4">Happy</text>
<text id="rating5">Very happy</text>
<text id="speedwavebegin">YOUR RESULT WILL BECOME PART OF A SPEED WAVE</text>
<text id="ping">PING</text>
<text id="hostedby">Hosted by</text>
<text id="counterdescription">TOTAL TESTS
TO DATE</text>
<text id="copied">COPIED</text>
<text id="autostartdesc">AUTO STARTING SPEED TEST IN</text>
<text id="seconds">SECONDS</text>
<text id="second">SECOND</text>
<text id="error">ERROR</text>
<text id="tryagain">Try Again</text>
<text id="share-wavetitle">START A SPEED WAVE</text>
<text id="share-namewave">Speed Wave Name</text>
<text id="share-waveresults">Your result is now part of the Speed Wave!</text>
<text id="compare-yourtest">Your Result</text>
<text id="survey-surveytitle">Help Us Understand Broadband Costs</text>
<text id="survey-downloadpackage">Download Package</text>
<text id="survey-uploadpackage">Upload Package</text>
<text id="survey-howmuch">How much do you pay?</text>
<text id="survey-includes">Includes:</text>
<text id="survey-postalcode">Is this your postal code?</text>
<text id="survey-submit">SUBMIT</text>
<text id="share-accounttitle">GET A FREE OOKLA SPEEDTEST ACCOUNT</text>
<text id="share-accountdescription">Being logged in would allow you to start a Speed Wave here!
Registration is free and only requires a valid email address.</text>
<text id="share-emailaddress">Your Email Address</text>
<text id="share-twitterurl">https://twitter.com/share?text=Check%20out%20my%20%40Ookla%20Speedtest%20result!%20What%27s%20your%20speed%3F&amp;url=http%3A%2F%2Fwww.speedtest.net%2Fmy-result%2F{RESULTID}&amp;related=ookla%3ACreators%20of%20Ookla%20Speedtest&amp;hashtags=speedtest</text>
<text id="share-facebookurl">https://www.facebook.com/dialog/feed?app_id=581657151866321&amp;link=http://www.speedtest.net/my-result/{RESULTID}&amp;description=This%20is%20my%20Ookla%20Speedtest%20result.%20Compare%20your%20speed%20to%20mine!&amp;redirect_uri=http://www.speedtest.net&amp;name=Check%20out%20my%20Ookla%20Speedtest%20results.%20What%27s%20your%20speed%3F</text>
<text id="share-viewwave">VIEW SPEED WAVE</text>
<text id="share-createwave">CREATE</text>
<text id="survey-speed">Speed</text>
<text id="survey-phone">Phone</text>
<text id="survey-tv">TV</text>
<text id="survey-package">What speeds do you pay for?</text>
<text id="survey-thanks">Thanks for participating in the survey!</text>
<text id="selectingbestserver">SELECTING BEST SERVER BASED ON PING</text>
<text id="compare-myresults">MY RESULTS</text>
<text id="share-createaccount">CREATE</text>
<text id="begintest-preferred">YOUR PREFERRED SERVER</text>
<text id="begintest-ping">RECOMMENDED SERVER</text>
<text id="connecting">CONNECTING</text>
<text id="share-copy">COPY</text>
<text id="endtest-share-button">SHARE THIS RESULT</text>
<text id="endtest-compare-button">COMPARE
YOUR RESULT</text>
<text id="endtest-contribute-button">CONTRIBUTE
TO NET INDEX</text>
<text id="close">CLOSE</text>
<text id="survey-retake">RETAKE THE
SURVEY</text>
<text id="share-link">IMAGE</text>
<text id="share-forum">FORUM</text>
<text id="share-wavedescription">Use this test result to begin your own Speed Wave!</text>
<text id="pcmagmessage">Fastest ISPs</text>
<text id="panel0">wave</text>
<text id="panel1">share</text>
<text id="panel2">link:{LANG_CODE}/results.php?source=compare</text>
<text id="panel3">contribute</text>
<text id="bitspersecond">bits per second</text>
<text id="endtest">standard</text>
<text id="lang">en</text>
<text id="share-pinteresturl">http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fwww.speedtest.net%2F&amp;media=http%3A%2F%2Fspeedtest.net%2Fresult%2F{RESULTID}.png&amp;description=Check%20out%20my%20result%20from%20Ookla%20Speedtest!</text>
<text id="panelsuffix"></text>
<text id="survey-nextbtn">Continue</text>
<text id="survey-editbtn">EDIT</text>
<text id="survey-download">Download</text>
<text id="survey-download-validate">Download:</text>
<text id="survey-upload">Upload</text>
<text id="survey-upload-validate">Upload:</text>
<text id="survey-connectiontype">Connection Type?</text>
<text id="survey-q1label1">Home</text>
<text id="survey-q1label2">Business</text>
<text id="survey-q1label3">School</text>
<text id="survey-q1label4">Public Wi-Fi</text>
<text id="survey-q1label5">Other</text>
<text id="survey-ispconf">My ISP is:</text>
<text id="survey-q2label1">Yes</text>
<text id="survey-q2label2">Wrong</text>
<text id="survey-q3label1">Yes</text>
<text id="survey-q3label2">Wrong</text>
<text id="survey-postalcode-input">Please enter your postal code</text>
<text id="survey-labelispinput">Please enter your ISP name</text>
<text id="survey-okbtn">OK</text>
<text id="survey-validationUploadline1">Please check your upload speed.
  This seems faster than expected.</text>
<text id="survey-validationAmountline1">Please check the amount entered.
    This seems higher than expected.</text>
<text id="survey-validationDownloadline1">Please check your Download speed.
  This seems faster than expected.</text>
<text id="share-web">WEB</text>
<text id="share-html">EMBED</text>
<text id="endtest-contribute-are-you-on">Are you on</text>
<text id="endtest-contribute-take-survey">Take our Broadband Internet Survey!</text>
<text id="endtest-test-again">TEST AGAIN</text>
<text id="endtest-compare">COMPARE</text>
</translation>
</settings>
Traceback (most recent call last):
  File "/usr/local/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 1418, in main
    shell()
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 1329, in shell
    speedtest = Speedtest()
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 702, in __init__
    self.get_config()
  File "/usr/local/lib/python2.7/site-packages/speedtest.py", line 742, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 3, column 64
```

**Comment by glyndon** [comment]
Working again here, too.

**Comment by willprice** [comment]
Weird, I'm seeing the same issue now:

```
wp@viki:~$ ~/.local/bin/speedtest-cli
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/home/wp/.local/bin/speedtest-cli", line 11, in <module>
    sys.exit(main())
  File "/home/wp/.local/lib/python2.7/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/home/wp/.local/lib/python2.7/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/home/wp/.local/lib/python2.7/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/home/wp/.local/lib/python2.7/site-packages/speedtest.py", line 783, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: undefined entity &copy;: line 85, column 7241
```

**Comment by glyndon** [comment]
Perhaps I closed this case prematurely.

**Comment by Chadster766** [comment]
On Debian 9 I'm seeing the below errors:

```
root@MCDEBIAN:~# speedtest-cli
Retrieving speedtest.net configuration...
Testing from I-Net Link Wireless (208.92.136.145)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Westman Communications (Brandon, MB) [84.52 km]: 61.596 ms
Testing download speed................................................................................
Download: 13.20 Mbit/s
Testing upload speedTraceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.0', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1400, in main
    shell()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1376, in shell
    speedtest.upload(callback=callback)
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1086, in upload
    data._create_data()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 497, in _create_data
    (chars * multiplier)[0:int(self.length) - 9]
MemoryError
root@MCDEBIAN:~#
```

**Comment by Chadster766** [comment]
Using your latest version resolved the issue. Thanks work your work on this :smile:
