### ISSUE TITLE
Config retrieval error

### ISSUE THREAD

**Issue by mikkelam** [sivel/speedtest-cli#460]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/speedtest.py", line 1401, in shell
    speedtest = Speedtest()
  File "/usr/local/lib/python3.4/dist-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/local/lib/python3.4/dist-packages/speedtest.py", line 765, in get_config
    raise ConfigRetrievalError(e)
speedtest.ConfigRetrievalError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/speedtest.py", line 1498, in main
    shell()
  File "/usr/local/lib/python3.4/dist-packages/speedtest.py", line 1402, in shell
    except (ConfigRetrievalError, HTTP_ERRORS):
```

I believe it happens due to poor internet connectivity

**Comment by sivel** [comment]
The traceback is resolved in the branch that will become the next release, however this is still an error, indicating that retrieving the config timed out, likely, as you say, related to poor internet connectivity.

**Comment by mikkelam** [comment]
Awesome, thanks for the quick reply!
