### ISSUE TITLE
EOFError downloading server list

### ISSUE THREAD

**Issue by dbeckwith** [sivel/speedtest-cli#465]
```console
$ speedtest
Retrieving speedtest.net configuration...
Testing from Falco Networks (85.203.23.57)...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1498, in main
    shell()
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 1436, in shell
    speedtest.get_servers(servers)
  File "/usr/local/lib/python3.6/site-packages/speedtest.py", line 889, in get_servers
    serversxml.append(stream.read(1024))
  File "/usr/local/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/local/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

Seems like this isn't really `speedtest`'s fault, but how can I fix this? Is there another server URL I should use or something?

**Comment by sivel** [comment]
You might try adding `--secure` and see if that help resolve the problem.

I'll keep this open, as it looks like I should handle that specific exception also.

**Comment by dbeckwith** [comment]
The `--secure` flag doesn't help, I get the same error.

**Comment by sivel** [comment]
This exception should be handled more gracefully in the no-globals branch that will be merged to devel for the next release.
