### ISSUE TITLE
Parse error when the ISP is "AT&T U-verse".

### ISSUE THREAD

**Issue by JeffByers-SF** [sivel/speedtest-cli#491]
Parse error when the ISP is "AT&T U-verse".

I cannot run 'speedtest.py' when the ISP is "AT&T U-verse", I
get the parse error:

Traceback (most recent call last):
  File "/usr/bin/speedtest.py", line 1504, in <module>
    main()
  File "/usr/bin/speedtest.py", line 1494, in main
    shell()
  File "/usr/bin/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/usr/bin/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/bin/speedtest.py", line 783, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 85, in XML
SyntaxError: not well-formed (invalid token): line 3, column 65

The problem is the isp= attribute having an unescaped '&' in it.

\<client ip="172.125.82.253" lat="37.312" lon="-121.966" isp="AT&T U-verse" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="US" /\>

Not sure if the server is sending this down unescaped, or if
the header processing is removing the escapes, which then need
to be re-added before being parsed as XML.

**Comment by samwiseg00** [comment]
i have the same problem...

```
DEBUG: <?xml version="1.0" encoding="UTF-8"?>
<settings>
<client ip="1.1.1.1" lat="32.3284" lon="-80.2459" isp="AT&T Internet Services" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="US" />
```

```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 1494, in main
    shell()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 1397, in shell
    speedtest = Speedtest()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/lib/python2.7/site-packages/speedtest.py", line 783, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 3, column 65
```

**Comment by suneettipirneni** [comment]
I have the same exact problem also :)

```
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1498, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1401, in shell
    speedtest = Speedtest()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 743, in __init__
    self.get_config()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 783, in get_config
    root = ET.fromstring(''.encode().join(configxml))
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 3, column 67
```

**Comment by sivel** [comment]
This seems to be a problem with the data that speedtest.net is sending.

I however cannot duplicate this on my AT&T connection:

```
<client ip="x.x.x.x" lat="29.5559" lon="-98.3652" isp="AT&amp;T U-verse" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="US" />
```

I'm not sure that I can do anything here.  Other than adding additional error handling to not show a traceback, and instead provide a more friendly error.

**Comment by samwiseg00** [comment]
Looks like speedtest changed it back around midnight ET. At lest for me. 

```
DEBUG: Config XML:
b'<?xml version="1.0" encoding="UTF-8"?>\n<settings>\n<client ip="1.1.1.1" lat="32.3284" lon="-80.1459" isp="AT&amp;T Internet Services" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="US" />\n<server-config threadcount="4"
```

**Comment by sivel** [comment]
I've just pushed a change to the devel branch to gracefully handle XML parsing errors.  It will be included in the next bugfix release.

**Comment by JeffByers-SF** [comment]
I confirmed that today the isp= string returned from the Speedtest server is correctly escaped for me as well.
