### ISSUE TITLE
Memory allocation issues even with '--no-pre-allocate'

### ISSUE THREAD

**Issue by gsbabil** [sivel/speedtest-cli#499]
Hi @sivel,

Thanks for your handy speedtest.net client tool.

I'm on version `2.0.0`, and getting the following memory allocation
errors, mostly during upload. The exceptions occur even after using
`--no-pre-allocate`.

Please have a look. Thank you.

P.S.

I'm able to run an older version `0.3.1` of `speedtest-cli` from
Debian Jessie repository, and there is no memory allocation problem
on the same machine.

```
$ speedtest-cli --no-pre-allocate --json

Exception in thread Thread-86:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 823, in run
    f = self._opener(request)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 464, in http_open
    req
  File "/usr/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 883, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in send
    datablock = data.read(blocksize)
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 784, in read
    chunk = self.data.read(n)
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 778, in data
    self.pre_allocate()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 771, in pre_allocate
    'Insufficient memory to pre-allocate upload data. Please '
SpeedtestCLIError: Insufficient memory to pre-allocate upload data. Please use --no-pre-allocate

Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==2.0.0', 'console_scripts', 'speedtest-cli')()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1832, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1802, in shell
    speedtest.upload(callback=callback, pre_allocate=args.pre_allocate)
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1523, in upload
    self.results.bytes_sent = sum(finished)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by sivel** [comment]
Not sure there is anything that can be done, other than maybe addressing an issue with the error.

Only so much can be done to reduce the memory footprint.  You need at least around 100-150MB of available memory to populate the tests with enough data.  `--no-pre-allocate` just prevents speedtest-cli from allocating data for all upload tests that it will perform, and offloads generation of the data to when the upload starts.

Perhaps disable the upload test with `--no-upload`
