### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'source_address'

### ISSUE THREAD

**Issue by eghetto** [sivel/speedtest-cli#513]
Recently it's constantly failing with:

```
Retrieving speedtest.net server list...
Selecting best server based on ping...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 1843, in <module>
    main()
  File "/usr/local/bin/speedtest-cli", line 1832, in main
    shell()
  File "/usr/local/bin/speedtest-cli", line 1779, in shell
    speedtest.get_best_server()
  File "/usr/local/bin/speedtest-cli", line 1347, in get_best_server
    source_address=source_address_tuple
TypeError: __init__() got an unexpected keyword argument 'source_address'
```

Using version 2.0.0

Thanks!

**Comment by sivel** [comment]
Can you give me information about python version, OS, and where/how you got python?

**Comment by eghetto** [comment]
Thanks for the quick reply! Here you go:

```
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
```

```
CentOS release 6.5 (Final)
Linux my 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
centos-release-6-5.el6.centos.11.1.x86_64
```

Got python via:
`yum install python`
