### ISSUE TITLE
Unable to run with --secure parameter on v2.0.1 on macOS+Homebrew

### ISSUE THREAD

**Issue by cc452** [sivel/speedtest-cli#517]
I'm not familiar enough with Python at the moment to decipher the traceback messages, so I'll paste them below. Simply put, after updating from 2.0 to 2.0.1, the `--secure` parameter breaks the program with the following:

> $ speedtest-cli --secure
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 1890, in <module>
    main()
  File "/usr/local/bin/speedtest-cli", line 1879, in main
    shell()
  File "/usr/local/bin/speedtest-cli", line 1775, in shell
    secure=args.secure
  File "/usr/local/bin/speedtest-cli", line 1022, in `__init__`
    self.get_config()
  File "/usr/local/bin/speedtest-cli", line 1055, in get_config
    uh, e = catch_request(request, opener=self._opener)
  File "/usr/local/bin/speedtest-cli", line 663, in catch_request
    uh = _open(request)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/speedtest-cli", line 502, in https_open
    req
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/local/bin/speedtest-cli", line 440, in connect
    self.sock = self._context.wrap_socket(self.sock, **kwargs)
AttributeError: 'NoneType' object has no attribute 'wrap_socket'
$

I haven't had a chance to test this on other macOS systems yet, but with how fresh 2.0.1 is, I thought it might be useful to post this now.

If it's just me, let me know!

Edit: For better markdown of `__init__`

**Comment by btoplak** [comment]
The same error here, but no parameters at all:

`
Ubuntu-1804-bionic-64-minimal ~ # speedtest-cli
Retrieving speedtest.net configuration...
Testing from Hetzner Online GmbH (176.9.126.245)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1879, in main
    shell()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1825, in shell
    speedtest.get_best_server()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 1403, in get_best_server
    h.request("GET", path, headers=headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/speedtest.py", line 440, in connect
    self.sock = self._context.wrap_socket(self.sock, **kwargs)
AttributeError: 'NoneType' object has no attribute 'wrap_socket'
`

**Comment by sivel** [comment]
Thanks for the report.  I'll look into this and try to get a fix out soon.

**Comment by sivel** [comment]
Can you please test with https://raw.githubusercontent.com/sivel/speedtest-cli/devel/speedtest.py and let me know if it resolves your issues?

**Comment by cc452** [comment]
@sivel The version in that link (using --secure) does indeed work as expected. Thanks!

**Comment by sivel** [comment]
v2.0.2 has been released.

**Comment by btoplak** [comment]
v.2.0.2 works now for me to, thank you @sivel !
