### ISSUE TITLE
NameError on No internet Connection

### ISSUE THREAD

**Issue by alichtman** [sivel/speedtest-cli#563]
```bash
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/local/bin/speedtest", line 1895, in <module>
    main()
  File "/usr/local/bin/speedtest", line 1884, in main
    shell()
  File "/usr/local/bin/speedtest", line 1780, in shell
    secure=args.secure
  File "/usr/local/bin/speedtest", line 1027, in __init__
    self.get_config()
  File "/usr/local/bin/speedtest", line 1101, in get_config
    except ExpatError:
NameError: global name 'ExpatError' is not defined
```

**Comment by sivel** [comment]
Can you provide some more information?

1. What OS are you using?
2. What version of python (`python -V`)?
3. How did you install speedtest-cli?

**Comment by alichtman** [comment]
I can no longer replicate this. Maybe just ignore?

1. MacOS Mojave 10.14.1
2. Python 2.7.15
3. `brew install speedtest-cli`
