### ISSUE TITLE
ModuleNotFoundError: No module named 'speedtest'

### ISSUE THREAD

**Issue by joshuambg** [sivel/speedtest-cli#566]
Windows 10 
Git install exactly as described in readme

```
>python --version
Python 3.7.2
>speedtest-cli -h
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python37\Scripts\speedtest-cli-script.py", line 11, in <module>
    load_entry_point('speedtest-cli==2.0.2', 'console_scripts', 'speedtest-cli')()
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'speedtest'
```

**Comment by sivel** [comment]
The instructions do appear to be slightly incorrect.  They should be:

```
git clone https://github.com/sivel/speedtest-cli.git
cd speedtest-cli
python setup.py install
```
