### ISSUE TITLE
Upload speed -- ERROR

### ISSUE THREAD

**Issue by mb13** [sivel/speedtest-cli#575]
I'm using `speedtest-cli` on my AC86U router (aarch64). The download is working fine. However I'm receiving the following error message for upload:

`Testing upload speedERROR: Insufficient memory to pre-allocate upload data. Please use --no-pre-allocate`

If I run it `speedtest-cli --no-pre-allocate` then I will have these errors:

Exception in thread Thread-67:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/lib/python2.7/site-packages/speedtest.py", line 841, in run
    f = self._opener(request)
  File "/opt/lib/python2.7/urllib2.py", line 429, in open
  File "/opt/lib/python2.7/urllib2.py", line 447, in _open
  File "/opt/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/opt/lib/python2.7/site-packages/speedtest.py", line 482, in http_open
    req
  File "/opt/lib/python2.7/urllib2.py", line 1195, in do_open
  File "/opt/lib/python2.7/httplib.py", line 1042, in request
  File "/opt/lib/python2.7/httplib.py", line 1082, in _send_request
  File "/opt/lib/python2.7/httplib.py", line 1038, in endheaders
  File "/opt/lib/python2.7/httplib.py", line 886, in _send_output
  File "/opt/lib/python2.7/httplib.py", line 853, in send
  File "/opt/lib/python2.7/site-packages/speedtest.py", line 802, in read
    chunk = self.data.read(n)
  File "/opt/lib/python2.7/site-packages/speedtest.py", line 796, in data
    self.pre_allocate()
  File "/opt/lib/python2.7/site-packages/speedtest.py", line 789, in pre_allocate
    'Insufficient memory to pre-allocate upload data. Please '
SpeedtestCLIError: Insufficient memory to pre-allocate upload data. Please use --no-pre-allocate

Exception in thread Thread-68:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/lib/python2.7/site-packages/speedtest.py", line 841, in run
    f = self._opener(request)
  File "/opt/lib/python2.7/urllib2.py", line 429, in open
  File "/opt/lib/python2.7/urllib2.py", line 447, in _open
...
...

What's wrong?

**Comment by faiyeah** [comment]
I echo this problem as well. Inspecting the source code, it seems the script will touch the pre_allocate memory logic even with the option passed.

**Comment by mb13** [comment]
thx, actually I'm using Merlin/entware

**Comment by faiyeah** [comment]
Culprit is found:
`
    @property
    def data(self):
        if not self._data:
            self.pre_allocate()  <----
        return self._data
`
With --no-pre-allocate, the self._data is not filled with data, but calling the data() will trigger the same piece of pre_allocate code, which trigger the issue.

**Comment by sivel** [comment]
This indicates your system is too memory constrained to run this tool.  With `--no-pre-allocate` we only allocate the data as needed, whereas without that option, we allocate it for all requests before they even need it.

**Comment by rraallvv** [comment]
I'm seeing this exception, is it related to this issue?

```
Retrieving speedtest.net configuration...
Testing from Multacom Corporation (154.90.14.41)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Cellcard (Phnom Penh) [161.49 km]: 512.682 ms
Testing download speed.........Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./speedtest.py", line 810, in run
    f = self._opener(self.request)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "./speedtest.py", line 543, in http_open
    req
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./speedtest.py", line 810, in run
    f = self._opener(self.request)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "./speedtest.py", line 543, in http_open
    req
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

.......................................................................
Download: 0.08 Mbit/s
Testing upload speed................................................................................................
Upload: 0.71 Mbit/s
```

**Comment by rraallvv** [comment]
Also, is there a way to make speedtest-cli to cache the speedtest configuration? That way calling the command multiple times in a row for testing a list of proxies would be faster.

**Comment by melonius** [comment]
Thanks Sivel for your work.
in debian 10 buster the upload speed fails (in my case i have 100Mb and reports 4Mb)
whith -no-pre-allocate the same result.

**Comment by melonius** [comment]
I have instaled the latest version 2.1.2 and all works fine.
Thanks

**Comment by Floppyjoe** [comment]
Why would this tool need an exorbitant amount of memory to run a simple speed test? My problem probably fall in your too lazy to fix category. =)

**Comment by nikolajsheller** [comment]
2.1.1 also seems to resolve the issue.
