### ISSUE TITLE
--no-pre-allocate not working

### ISSUE THREAD

**Issue by manderss99** [sivel/speedtest-cli#593]
see log (removed my ip address):

root@GL-AR750S:~# ./speedtest.py --no-pre-allocate
Retrieving speedtest.net configuration...
Testing from Bredbandsbolaget AB (x.x.x.x)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Tele2 (Kista) [4.71 km]: 18.451 ms
Testing download speed................................................................................
Download: 29.90 Mbit/s
Testing upload speed.........................................................................Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "./speedtest.py", line 867, in run
    f = self._opener(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "./speedtest.py", line 505, in http_open
    req
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
  File "/usr/lib/python2.7/httplib.py", line 886, in _send_output
  File "/usr/lib/python2.7/httplib.py", line 853, in send
  File "./speedtest.py", line 828, in read
    chunk = self.data.read(n)
  File "./speedtest.py", line 822, in data
    self.pre_allocate()
  File "./speedtest.py", line 815, in pre_allocate
    'Insufficient memory to pre-allocate upload data. Please '
SpeedtestCLIError: Insufficient memory to pre-allocate upload data. Please use --no-pre-allocate

Exception in thread Thread-77:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "./speedtest.py", line 867, in run
    f = self._opener(request)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "./speedtest.py", line 505, in http_open
    req
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
  File "/usr/lib/python2.7/httplib.py", line 886, in _send_output
  File "/usr/lib/python2.7/httplib.py", line 853, in send
  File "./speedtest.py", line 828, in read
    chunk = self.data.read(n)
  File "./speedtest.py", line 822, in data
    self.pre_allocate()
  File "./speedtest.py", line 815, in pre_allocate
    'Insufficient memory to pre-allocate upload data. Please '
SpeedtestCLIError: Insufficient memory to pre-allocate upload data. Please use --no-pre-allocate

......................
.Traceback (most recent call last):
  File "./speedtest.py", line 1944, in <module>
    main()
  File "./speedtest.py", line 1930, in main
    shell()
  File "./speedtest.py", line 1898, in shell
    threads=(None, 1)[args.single]
  File "./speedtest.py", line 1608, in upload
    self.results.bytes_sent = sum(finished)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by sivel** [comment]
Just because you are running out of memory, does not mean that `--no-pre-allocate` is not working.  Pre allocation means that all data used for upload tests is allocated before any tests start, which does require more memory.

However, `--no-pre-allocate` only allocates memory for the requests that are executing, which is possible that it still consumes too much memory for your host.

This indicates that your host is too memory restricted for these tests to work.

You may benefit from the new `--single` option, but that will produce different results, as it simulates only a single download, and likely cannot saturate your link.
