### ISSUE TITLE
Error while using --secure

### ISSUE THREAD

**Issue by Imparium** [sivel/speedtest-cli#608]
I am on a Raspberry Pi 3, and when using just "speedtest" I get satisfactory results, however while using the arg --secure, I get this:
```
pi@raspberrypi:~ $ speedtest-cli --secure
Retrieving speedtest.net configuration...
Testing from PaintWeb Internet Ltda (189.50.158.51)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 11, in <module>
    load_entry_point('speedtest-cli==1.0.0', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1400, in main
    shell()
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1364, in shell
    '%(latency)s ms' % results.server, quiet)
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 1253, in printer
    print_(out, **kwargs)
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 204, in print_
    write(arg)
  File "/usr/lib/python2.7/dist-packages/speedtest.py", line 169, in write
    data = data.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 29: ordinal not in range(128)

```
Running version: 1.0.0-1

**Comment by sivel** [comment]
This was resolved in the v1.0.4 release. Please upgrade to a newer version.  The current version of speedtest-cli is 2.1.1.
