### ISSUE TITLE
add ISP speedtest R Mundo

### ISSUE THREAD

**Issue by manches** [sivel/speedtest-cli#625]
Hi.

My local ISP company has a speedtest server that goes though Ookla on the URL
https://mundo-r.speedtestcustom.com/

I have tried with the option mini or sourece

`:~/speedtest-cli# python speedtest.py --mini https://stvelocimetro.mundo-r.com
Retrieving speedtest.net configuration...
Testing from Contabo GmbH (207.180.248.139)...
Traceback (most recent call last):
  File "speedtest.py", line 1944, in <module>
    main()
  File "speedtest.py", line 1930, in main
    shell()
  File "speedtest.py", line 1871, in shell
    speedtest.get_best_server(speedtest.set_mini_server(args.mini))
  File "speedtest.py", line 1338, in set_mini_server
    text.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 431: ordinal not in range(128)`

`~/speedtest-cli# python speedtest.py --mini 151.101.114.219 
Retrieving speedtest.net configuration...
Testing from Contabo GmbH (207.180.248.139)...
Traceback (most recent call last):
  File "speedtest.py", line 1944, in <module>
    main()
  File "speedtest.py", line 1930, in main
    shell()
  File "speedtest.py", line 1871, in shell
    speedtest.get_best_server(speedtest.set_mini_server(args.mini))
  File "speedtest.py", line 1328, in set_mini_server
    request = build_request(url)
  File "speedtest.py", line 654, in build_request
    if url[0] == ':':
IndexError: string index out of range`

`~/speedtest-cli# python speedtest.py --source 151.101.114.219 
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [Errno 99] Cannot assign requested address>
`

Has anyone had the same problem?
I have checked other issues but with no luck

**Comment by sivel** [comment]
Speedtest Custom is not current supported. See https://github.com/sivel/speedtest-cli/pull/498
