### ISSUE TITLE
Failure with httplib.BadStatusLine

### ISSUE THREAD

**Issue by HughWarrington** [sivel/speedtest-cli#689]
```
$ speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from EE Mobile (x.x.x.x)...
Selecting best server based on latency...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==0.3.4', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/speedtest_cli.py", line 790, in main
    speedtest()
  File "/usr/lib/python2.7/dist-packages/speedtest_cli.py", line 703, in speedtest
    best = getBestServer(servers)
  File "/usr/lib/python2.7/dist-packages/speedtest_cli.py", line 514, in getBestServer
    r = h.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
$ speedtest-cli --version
0.3.4
$ python --version
Python 2.7.12
```

Related to #86 maybe?

**Comment by Dmole** [comment]
Past time to use a normal https speed test.

**Comment by Dmole** [comment]
An alternative;
https://www.dslreports.com/forum/r30837078-Binaries-version-23th-December-is-posted
[dslrcli-linux-amd64.zip](https://github.com/sivel/speedtest-cli/files/4304130/dslrcli-linux-amd64.zip)
