### ISSUE TITLE
error while execution 

### ISSUE THREAD

**Issue by heapxor** [sivel/speedtest-cli#698]
It worked fine, nothing was upgraded changed... and it is not working anymore...

volumio@volumio:~$ host speedtest.net
speedtest.net has address 151.101.130.219
speedtest.net has address 151.101.194.219
speedtest.net has address 151.101.2.219
speedtest.net has address 151.101.66.219
speedtest.net has IPv6 address 2a04:4e42:400::731
speedtest.net has IPv6 address 2a04:4e42:200::731
speedtest.net has IPv6 address 2a04:4e42:600::731
speedtest.net has IPv6 address 2a04:4e42::731
speedtest.net mail is handled by 1 aspmx.l.google.com.
speedtest.net mail is handled by 10 aspmx2.googlemail.com.
speedtest.net mail is handled by 5 alt1.aspmx.l.google.com.
speedtest.net mail is handled by 5 alt2.aspmx.l.google.com.
volumio@volumio:~$ ping speedtest.net
PING speedtest.net (151.101.130.219) 56(84) bytes of data.
64 bytes from 151.101.130.219: icmp_seq=1 ttl=53 time=66.8 ms
^C
--- speedtest.net ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 66.890/66.890/66.890/0.000 ms
volumio@volumio:~$

volumio@volumio:~$ speedtest-cli
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 9, in <module>
    load_entry_point('speedtest-cli==0.3.1', 'console_scripts', 'speedtest-cli')()
  File "/usr/lib/python2.7/dist-packages/speedtest_cli.py", line 686, in main
    speedtest()
  File "/usr/lib/python2.7/dist-packages/speedtest_cli.py", line 536, in speedtest
    servers = closestServers(config['client'])
  File "/usr/lib/python2.7/dist-packages/speedtest_cli.py", line 345, in closestServers
    uh = urlopen('http://www.speedtest.net/speedtest-servers-static.php')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
volumio@volumio:~$

**Comment by sivel** [comment]
This is a transient issue with speedtest.net. I have no affiliation with Ookla, and cannot comment further about why it happens or happened.
