### ISSUE TITLE
It is not known how to use the API. Error

### ISSUE THREAD

**Issue by Salim9304** [sivel/speedtest-cli#737]
I wanted to test speed with python.
I used the code from the wiki
https://github.com/sivel/speedtest-cli/wiki

`pip3 install speedtest-cli`
Requirement already satisfied: speedtest-cli in /usr/lib/python3/dist-packages (2.1.1)
```
import speedtest

servers = []
# If you want to test against a specific server
# servers = [1234]

threads = None
# If you want to use a single threaded test
# threads = 1

s = speedtest.Speedtest()
s.get_servers(servers)
s.get_best_server()
s.download(threads=threads)
s.upload(threads=threads)
s.results.share()

results_dict = s.results.dict()
```
I get an error:
```
Traceback (most recent call last):
  File "/home/users/idlex-1.18/speedtest.py", line 1, in <module>
    import speedtest
  File "/users/idlex-1.18/speedtest.py", line 11, in <module>
    s = speedtest.Speedtest()
AttributeError: module 'speedtest' has no attribute 'Speedtest'
>>> 
```

**Comment by Comaxim** [comment]
Try:
```
from speedtest import Speedtest
```
and assign s with Speedtest().

**Comment by Salim9304** [comment]
no.
file name should be "speedtest"
