### ISSUE TITLE
http.client.BadStatusLine exception during SpeedTest class upload/download call

### ISSUE THREAD

**Issue by scottlinuxden** [sivel/speedtest-cli#752]
I have an application that is running a speed test periodically (every 10 minutes) and on some calls to Speedtest download or upload methods and I get the tracebacks below.  I have wrapped the call in an exception handler and can handle the exception that way but I thought I would let you know that it might be an improvement to return a bad status or Speedtest declared exception so it is more specific to caller on what the issue is.  It appears to be a garbled status line from the server upload/download test that is causing the issue.  I am at this point handling this as a server response issue on the other end of the test but thought I would bring this up.  

See tracebacks below:

Another traceback from another call from application where I am using Speedtest-cli:
Exception in thread Thread-23226:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.7/site-packages/speedtest.py", line 905, in run
    f = self._opener(request)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/speedtest.py", line 543, in http_open
    req
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: LÌQ°já¦$î¯)wHTTP/1.1 200 OK

Another traceback from another call from application where I am using Speedtest-cli:

Exception in thread Thread-17255:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.7/site-packages/speedtest.py", line 905, in run
    f = self._opener(request)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/speedtest.py", line 543, in http_open
    req
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: @L(ü¹Þ}üÀYùÛà\eK\gË0§Kkú¢xÅÿÕmD8³¯*1¹ª­?:)M70ÐãA,ué¹Ô r@£|¦¯9Ã¬¸C Óè^ª|¦ø1_Á¢ÊÃ*[¡$·Tpe#$]ÞÐ@úÑÂÎ#Ó$=àÏ)Ùu^·¦@~ûEÖÜòï4÷©F¼9÷Ò~jëð)ûÌz'a	Ñ|ôÛ¬ÌÿÏOLF>Yß1$C?/ç;§ð\ü¦î9õeûzâkwbvüÏøpz©dÃZoy¥%»:üi¯tóài­é)1ÀS[zuEG¾OÖO

**Comment by jbylund** [comment]
half just to tag the thread here's another backtrace:
```
Traceback (most recent call last):
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/site-packages/speedtest.py", line 905, in run
    f = self._opener(request)
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/site-packages/speedtest.py", line 537, in http_open
    return self.do_open(
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ÖGA· ZËô¼Ñ`v¥HTTP/1.1 200 OK

Traceback (most recent call last):
  File "/home/jbylund/metrics_recorder.py", line 138, in <module>
    main()
  File "/home/jbylund/metrics_recorder.py", line 134, in main
    tr.update()
  File "/home/jbylund/metrics_recorder.py", line 118, in update
    s.upload(threads=threads)
  File "/home/jbylund/.pyenv/versions/3.8.5/lib/python3.8/site-packages/speedtest.py", line 1664, in upload
    self.results.bytes_sent = sum(finished)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
